#!/bin/bash
set -e
WEBDIR=/work/myweb
GUNICORN_CONFIG=/example/gunicorn_config.py

LOGFILE=$WEBDIR/logs/gunicorn.log
LOGDIR=$(dirname $LOGFILE)

cd $WEBDIR

test -d $LOGDIR || mkdir -p $LOGDIR
exec /home/www-data/.pyenv/versions/3.5.0/bin/gunicorn \
--worker-class aiohttp.worker.GunicornWebWorker \
--pythonpath /home/www-data/.pyenv/versions/3.5.0/lib/python3.5 \
--forwarded-allow-ips="127.0.0.1" \
--log-level=info --log-file=$LOGFILE server:my_web_app -c $GUNICORN_CONFIG
