version: "3.2"
services:
  mynginx:
    image: nginx
    volumes:
      - /my_path/nginx/mysite.conf:/etc/nginx/conf.d/mysite.conf:ro # conf
      - /my_path/nginx/my_share:/work/                     # link static folder
    ports:
      - "30080:80"
    restart: always
    environment:
      - NGINX_HOST=mywebsite.example.com
      - NGINX_PORT=80
      - SERVER_NAME=localhost
      - STATIC_PATH=/work/
    run: RUN echo '<h1>Hello, Docker!</h1>' > /usr/share/nginx/html/index.html
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  mypostgres:
    image: postgres
    volumes:
      - /my_path/postgres/data:/work/                      # db data
      - /my_path/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "35432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-database-password
      PGDATA: /work/
  mymongodb:
    image: mongo
    volumes:
      - /my_path/mongodb/data/db:/data/db                 # db data
    ports:
      - 32717:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/work/logs
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=my-database-password
  mydjango:
    build:
      context: .
      dockerfile: ./django/my_api_dockerfile.txt
    ports:
      - "38080:8080"
